code --install-extension James-Yu.latex-workshop
code --install-extension PKief.material-icon-theme
code --install-extension WakaTime.vscode-wakatime
code --install-extension abusaidm.html-snippets
code --install-extension ajshort.latex-preview
code --install-extension andischerer.theme-atom-one-dark
code --install-extension castwide.solargraph
code --install-extension chrmarti.regex
code --install-extension devine-davies.make-hidden
code --install-extension dkundel.vscode-new-file
code --install-extension donjayamanne.githistory
code --install-extension file-icons.file-icons
code --install-extension formulahendry.code-runner
code --install-extension fosshaas.fontsize-shortcuts
code --install-extension hackwaly.ocaml
code --install-extension HookyQR.beautify
code --install-extension hoovercj.ruby-linter
code --install-extension kaiwood.center-editor-window
code --install-extension karunamurti.rspec-snippets
code --install-extension ms-mssql.mssql
code --install-extension ms-python.python
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.node-debug2
code --install-extension ms-vsts.team
code --install-extension mshr-h.systemverilog
code --install-extension muchtrix.ocaml-tuareg-master
code --install-extension pkosta2005.heroku-command
code --install-extension pthorsson.vscode-jsp
code --install-extension rebornix.prolog
code --install-extension rebornix.Ruby
code --install-extension redhat.java
code --install-extension rid9.datetime
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension spywhere.mark-jump
code --install-extension steve8708.Align
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscodevim.vim
